In [1]:
from scipy.io import arff
import numpy as np
import random
from sklearn.naive_bayes import MultinomialNB, GaussianNB, BernoulliNB
from sklearn.svm import SVC, NuSVC, LinearSVC
from sklearn.metrics import confusion_matrix 

In [2]:
data,meta = arff.loadarff('spambase.arff')

In [3]:
#print(data)
#print(meta)

In [4]:
random.shuffle(data)
train = data[:3000]
test = data[3000:]
print(train.shape)
print(type(train[0]))

(3000,)
<class 'numpy.void'>


In [5]:
trainY = train['is_spam']
#print(trainY)

names = list(train.dtype.names)
trainX = train[names[:57]]
#print(trainX)

testY = test['is_spam']
#print(testY)

testX = test[names[:57]]
#print(testX)

In [6]:
np.set_printoptions(threshold=np.nan)
print(trainY.shape)

trainX = np.array(trainX.tolist())
testX = np.array(testX.tolist())
#print(trainX)

(3000,)


In [12]:
from sklearn.metrics import precision_recall_fscore_support
model = MultinomialNB()
model.fit(trainX,trainY)
prediction = model.predict(testX)
conf = confusion_matrix(testY,prediction)
print(conf)
accuracy = (conf[0][0] + conf[1][1])/(conf[0][0] + conf[1][1] + conf[0][1] + conf[1][0]) 
print('Accuracy = ',accuracy)
precision = conf[0][0]/(conf[0][0] + conf[0][1])*100
recall = conf[0][0]/(conf[0][0] + conf[1][0])*100

print('Precision =', precision )
print('Recall=', recall)
precision_recall_fscore_support(testY, prediction, average='weighted')

[[648 171]
 [127 655]]
Accuracy =  0.813866333542
Precision = 79.1208791209
Recall= 83.6129032258


(0.81505224001069787, 0.81386633354153659, 0.81384396687375038, None)

In [13]:
model2 = BernoulliNB()
model2.fit(trainX,trainY)
prediction = model2.predict(testX)
conf = confusion_matrix(testY,prediction)
print(conf)
accuracy = (conf[0][0] + conf[1][1])/(conf[0][0] + conf[1][1] + conf[0][1] + conf[1][0]) 
print('Accuracy = ',accuracy)
precision = conf[0][0]/(conf[0][0] + conf[0][1])*100
recall = conf[0][0]/(conf[0][0] + conf[1][0])*100

print('Precision =', precision )
print('Recall=', recall)
precision_recall_fscore_support(testY, prediction, average='weighted')

[[744  75]
 [ 86 696]]
Accuracy =  0.899437851343
Precision = 90.8424908425
Recall= 89.6385542169


(0.89948139920402181, 0.89943785134291065, 0.89941711766463672, None)

In [14]:
model3 = GaussianNB()
model3.fit(trainX,trainY)
prediction = model3.predict(testX)
conf = confusion_matrix(testY,prediction)
print(conf)
accuracy = (conf[0][0] + conf[1][1])/(conf[0][0] + conf[1][1] + conf[0][1] + conf[1][0]) 
print('Accuracy = ',accuracy)
precision = conf[0][0]/(conf[0][0] + conf[0][1])*100
recall = conf[0][0]/(conf[0][0] + conf[1][0])*100

print('Precision =', precision )
print('Recall=', recall)
precision_recall_fscore_support(testY, prediction, average='weighted')

[[640 179]
 [ 36 746]]
Accuracy =  0.865708931918
Precision = 78.1440781441
Recall= 94.674556213


(0.87823675691258452, 0.86570893191755149, 0.86491127834080039, None)

In [15]:
model4 = LinearSVC()
model4.fit(trainX,trainY)
prediction = model4.predict(testX)
conf = confusion_matrix(testY,prediction)
print(conf)
accuracy = (conf[0][0] + conf[1][1])/(conf[0][0] + conf[1][1] + conf[0][1] + conf[1][0]) 
print('Accuracy = ',accuracy)
precision = conf[0][0]/(conf[0][0] + conf[0][1])*100
recall = conf[0][0]/(conf[0][0] + conf[1][0])*100

print('Precision =', precision )
print('Recall=', recall)
precision_recall_fscore_support(testY, prediction, average='weighted')

[[478 341]
 [ 12 770]]
Accuracy =  0.779512804497
Precision = 58.3638583639
Recall= 97.5510204082


(0.83755343857755105, 0.77951280449718929, 0.77096465985204121, None)